TestPlatform/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings
from .views import index, register_request, user_page, your_page, users_page, ratings_page, edit_user_page, settings_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', users_page, name='users_page'),
    path('users/<int:user_id>/', user_page, name='user_page'),
    path('users/you/', your_page, name='your_page'),
    path('users/you/settings', settings_page, name='settings_page'),
    path('users/you/edit/', edit_user_page, name='edit_your_page'),
    path('ratings/', ratings_page, name='ratings_page'),
    path('tests/', include('tests.urls')),
    path('editor/', include('editor.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/', register_request, name='register'),
    path('', index)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

editor/urls.py
from django.shortcuts import redirect
from django.urls import path

from editor.views import editor_page, editor_not_allowed, editor_modal_window, create_project, open_project, \
    edit_project, open_task, edit_task, create_task, create_exercise, templates, stats, remove_project, remove_task, \
    remove_element, change_element, upload_project_description, upload_task_description, create_element, publish_project

app_name = 'editor'

urlpatterns = [
    path('', editor_page, name='index'),
    path('projects/', editor_page),
    path('projects/<int:project_id>/', open_project, name='open_project'),
    path('projects/<int:project_id>/create_task', create_task, name='create_task'),
    path('projects/<int:project_id>/remove_project', remove_project, name='remove_project'),
    path('projects/<int:project_id>/edit/', edit_project, name='edit_project'),
    path('projects/<int:project_id>/publish/', publish_project, name='publish_project'),
    path('projects/<int:project_id>/upload_description/', upload_project_description, name='upload_project_description'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', open_task, name='open_task'),
    path('projects/<int:project_id>/tasks/<int:task_id>/remove_task', remove_task, name='remove_task'),
    path('projects/<int:project_id>/tasks/<int:task_id>/remove_element', remove_element, name='remove_element'),
    path('projects/<int:project_id>/tasks/<int:task_id>/change_element', change_element, name='change_element'),
    path('projects/<int:project_id>/tasks/<int:task_id>/create_exercise', create_exercise, name='create_exercise'),
    path('projects/<int:project_id>/tasks/<int:task_id>/create_element', create_element, name='create_element'),
    path('projects/<int:project_id>/tasks/<int:task_id>/upload_description/', upload_task_description, name='upload_task_description'),
    path('projects/<int:project_id>/tasks/<int:task_id>/edit/', edit_task, name='edit_task'),
    path('create_project', create_project, name='create_project'),
    path('not_allowed', editor_not_allowed),
    path('templates', templates),
    path('stats', stats),
    path('modal_window', editor_modal_window)
]

templates/editor/project/task/task_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ task.name }}{% endblock %}

{% block css_styles %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'table.css' %}">
    <link rel="stylesheet" href="{% static 'editor/editor.css' %}">
    <link rel="stylesheet" href="{% static 'editor/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/header.css' %}">
    <link rel="stylesheet" href="{% static 'editor/project/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/project/task_page.css' %}">
    <link rel="stylesheet" href="{% static 'editor/task/edit_page.css' %}">
{% endblock %}

{% block content %}

    {% include 'editor/header.html' %}

    <div class="content">

        <p class="path">
            <a href="{% url 'editor:open_project' project_id=project.id %}" class="active-link">{{ project.project_name }}</a> >
            <a class="active-link" href="{% url 'editor:open_task' project_id=project.id task_id=task.id %}">{{ task.name }}</a>
        </p>

        <form class="preview-project" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <p class="task-number">Задание №{{ task.number }}</p>
            <div class="field">
                <p class="field_name">Название задания</p>
                <input type="text" name="name" maxlength="50" value="{{ task.name }}"/>
            </div>
            <div class="field">
                <p class="field_name">Заголовок</p>
                <input type="text" name="title" value="{{ task.title }}"/>
            </div>
            <input type="submit" class="button buttons-submit" value="Сохранить"/>
        </form>

    </div>

    {% include 'footer.html' %}

{% endblock %}

{% block js_scripts %}

{% endblock %}

templates/editor/project/task/task_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ task.title }}{% endblock %}

{% block css_styles %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'table.css' %}">
    <link rel="stylesheet" href="{% static 'editor/editor.css' %}">
    <link rel="stylesheet" href="{% static 'editor/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/header.css' %}">
    <link rel="stylesheet" href="{% static 'editor/project/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/project/task_page.css' %}">
    <link rel="stylesheet" href="{% static 'editor/project/elements.css' %}">
    <link rel="stylesheet" href="{% static 'modal_window.css' %}">
    <link rel="stylesheet" href="{% static 'editor/project/simplemde.min.css' %}">
{% endblock %}

{% block content %}

    {% include 'editor/header.html' %}

    <div class="content">

        <p class="path"><a href="{% url 'editor:open_project' project_id=project.id %}" class="active-link">{{ project.project_name }}</a> > {{ task.name }}</p>

        <section class="preview-project">
            <p class="task-number">Задание №{{ task.number }}</p>
            <p class="task-name">{{ task.title }}</p>
            <div class="buttons-edit">
                <div class="button button-change-info" data-url="{% url 'editor:edit_task' project_id=project.id task_id=task.id %}"></div>
                <div class="button button-remove" data-modalwindow="#remove_task"></div>
            </div>
        </section>

        <section class="tabs-menu unselectable">
            <header class="tabs-buttons">
                <h2 data-content="project-tasks" class="tab-button active">Схема</h2>
                <h2 data-content="edit-info" class="tab-button">Объяснение задания</h2>
            </header>
            <div class="tabs-line"></div>
        </section>

        <section class="tab project-tasks">
            <main>
                <div class="elements-list">
                    {% for element in elements %}
                        {{ element.render }}
                    {% endfor %}
                </div>
            </main>
            <div class="editor-buttons-list">
                <div class="button button-secondary button-editor button-create-exercise" data-modalwindow="#creation_exercise">
                    Создать упражнение
                </div>
                <div class="button button-secondary button-editor button-create-element" data-modalwindow="#creation_element">
                    Создать элемент
                </div>
            </div>
            <div class="button button-editor button-save-changes hidden" id="save_schema">
                Сохранить порядок элементов схемы
            </div>
        </section>

        <section class="tab edit-info tab-relative not-visible" id="#edit-info">
            <form action="upload_description/" method="POST" id="edit-info-form">
                {% csrf_token %}
                <button type="sumbit" name="SEND UPDATES" class="button button-save-md not-allowed">Сохранить</button>
                <textarea id="edit-info" name="markdown_field">
{{ task.description_md }}</textarea>
            </form>
        </section>

    </div>

    {% include 'editor/project/modal_window/creation_exercise.html' %}
    {% include 'editor/project/modal_window/creation_element.html' %}
    {% include 'editor/project/modal_window/remove_task.html' %}
    {% include 'editor/project/modal_window/remove_element.html' %}

    {% include 'footer.html' %}

{% endblock %}

{% block js_scripts %}
    <script src="{% static 'editor/project/tabs-menu.js' %}"></script>
    <script src="{% static 'editor/changes.js' %}"></script>
    <script src="{% static 'editor/project/elements.js' %}"></script>
    <script src="{% static 'editor/project/exercises-list.js' %}"></script>
    <script src="{% static 'editor/task/script.js' %}"></script>
    <script src="{% static 'editor/project/simplemde.min.js' %}"></script>
    <script src="{% static 'editor/project/md-editor.js' %}"></script>
{% endblock %}