TestPlatform/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import settings
from .views import index, register_request, user_page, your_page, users_page, ratings_page, edit_user_page, settings_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', users_page, name='users_page'),
    path('users/<int:user_id>/', user_page, name='user_page'),
    path('users/you/', your_page, name='your_page'),
    path('users/you/settings', settings_page, name='settings_page'),
    path('users/you/edit/', edit_user_page, name='edit_your_page'),
    path('ratings/', ratings_page, name='ratings_page'),
    path('tests/', include('tests.urls')),
    path('editor/', include('editor.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/', register_request, name='register'),
    path('', index)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

editor/urls.py
from django.shortcuts import redirect
from django.urls import path

from editor.views import editor_page, editor_not_allowed, editor_modal_window, create_project, open_project, \
    edit_project, open_task, edit_task, create_task, create_exercise, templates, stats, remove_project, remove_task, \
    remove_element, change_element, upload_project_description, upload_task_description, create_element, publish_project

app_name = 'editor'

urlpatterns = [
    path('', editor_page, name='index'),
    path('projects/', editor_page),
    path('projects/<int:project_id>/', open_project, name='open_project'),
    path('projects/<int:project_id>/create_task', create_task, name='create_task'),
    path('projects/<int:project_id>/remove_project', remove_project, name='remove_project'),
    path('projects/<int:project_id>/edit/', edit_project, name='edit_project'),
    path('projects/<int:project_id>/publish/', publish_project, name='publish_project'),
    path('projects/<int:project_id>/upload_description/', upload_project_description, name='upload_project_description'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', open_task, name='open_task'),
    path('projects/<int:project_id>/tasks/<int:task_id>/remove_task', remove_task, name='remove_task'),
    path('projects/<int:project_id>/tasks/<int:task_id>/remove_element', remove_element, name='remove_element'),
    path('projects/<int:project_id>/tasks/<int:task_id>/change_element', change_element, name='change_element'),
    path('projects/<int:project_id>/tasks/<int:task_id>/create_exercise', create_exercise, name='create_exercise'),
    path('projects/<int:project_id>/tasks/<int:task_id>/create_element', create_element, name='create_element'),
    path('projects/<int:project_id>/tasks/<int:task_id>/upload_description/', upload_task_description, name='upload_task_description'),
    path('projects/<int:project_id>/tasks/<int:task_id>/edit/', edit_task, name='edit_task'),
    path('create_project', create_project, name='create_project'),
    path('not_allowed', editor_not_allowed),
    path('templates', templates),
    path('stats', stats),
    path('modal_window', editor_modal_window)
]

editor/models.py
from django.db import models

# Create your models here.

editor/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from tests.models import Project, ProjectTask, BaseExercise, BaseElement, \
    ProjectChronologyExercise, ProjectMatchExercise, ProjectRadioExercise, \
    ProjectStatementsExercise, ProjectInputExercise, ProjectAnswerExercise, ProjectImagesExercise, \
    ProjectImagesExercise, PictureImagesExercise, ProjectTitleElement, ProjectPictureElement, \
    ProjectQuoteElement, ProjectDocumentElement, ProjectYandexMapsElement, ProjectMatchListExercise
from tests.models.base import BaseStaticElement


class CreationProjectForm(ModelForm):
    project_name = forms.CharField(max_length=100)
    description = forms.Textarea()
    icon = forms.ImageField()

    class Meta:
        model = Project
        fields = ('project_name', 'description', 'icon')


class EditProjectInfo(ModelForm):
    name = forms.TextInput()
    description = forms.Textarea()
    icon = forms.ImageField()

    class Meta:
        model = Project
        fields = ('name', 'description', 'icon')


class CreationTaskForm(ModelForm):
    name = forms.CharField(max_length=50)

    class Meta:
        model = ProjectTask
        fields = ('name',)


class EditTaskInfo(ModelForm):
    pass

    class Meta:
        model = ProjectTask
        fields = ('name', 'title')


class ExcludedModelForm(ModelForm):
    class Meta:
        fields = ['type', 'name', 'title']


class CreationExerciseForm(forms.Form):
    type = forms.ChoiceField(choices=BaseExercise.TYPES, required=True, label='Тип упражнения')
    name = forms.CharField(max_length=50, required=True, label='Название')
    title = forms.CharField(max_length=150, required=False, label='Заголовок (необязательно)')

    def get_exercise(self):
        exercise = eval(f'Project{BaseExercise.CLASSES[int(self.cleaned_data["type"])]}()')
        exercise.type = self.cleaned_data['type']
        exercise.name = self.cleaned_data['name']
        exercise.title = self.cleaned_data['title']
        return exercise


class CreationStaticElementForm(forms.Form):
    type = forms.ChoiceField(choices=BaseStaticElement.TYPES, required=True, label='Тип статичного элемента')

    def get_element(self):
        element = eval(f'Project{BaseStaticElement.CLASSES[int(self.cleaned_data["type"])]}()')
        element.type = self.cleaned_data['type']
        return element


class CheckMarkDownForm(forms.Form):
    markdown_field = forms.Textarea()

editor/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.urls import reverse

from editor.forms import CreationProjectForm, CreationTaskForm, EditTaskInfo, EditProjectInfo, CreationExerciseForm, \
    CheckMarkDownForm, CreationStaticElementForm

from tests.models import Project, ProjectTask, ProjectTaskElement, BaseExercise, BaseStaticElement, \
    ChronologyExercise, MatchExercise, InputExercise, AnswerExercise, RadioExercise, StatementsExercise, \
    ImagesExercise, TitleElement, PictureElement, QuoteElement, DocumentElement, YandexMapsElement, \
    MatchListExercise


@login_required
def editor_page(request):
    template = loader.get_template('editor/tests_table.html')

    columns = ['ID', 'Название', 'Заданий', 'Дата создания', 'Изменено']
    published_tests_data = []
    development_tests_data = []

    projects = Project.objects.filter(author_id=request.user.id)

    for project in projects:
        if project.published:
            published_tests_data.append(project.get_json())
        else:
            development_tests_data.append(project.get_json())

    tests_context = {
        'columns': columns,
        'type': 'tests-list',
        'class': 'development_tests'
    }

    context = {
        'published_tests_table': template.render({**tests_context, 'rows': published_tests_data}),
        'development_tests_table': template.render({**tests_context, 'rows': development_tests_data}),
        'published_tests_exists': len(published_tests_data) != 0,
        'development_tests_exists': len(development_tests_data) != 0
    }

    return render(request, template_name='editor/editor.html', context=context)


@login_required
def create_project(request):
    if not request.POST:
        return render(request, template_name='editor/creation_project.html')

    project = Project(author=request.user)
    form = CreationProjectForm(request.POST, request.FILES, instance=project)

    project = Project.create(form)

    if not project is None:
        return redirect(reverse('editor:open_project', kwargs={'project_id': project.id}))


@login_required
def remove_project(request, project_id):
    if request.POST:
        project = Project.objects.get(id=project_id)
        if project.project_name == request.POST.get('input_projectname', None):
            project.delete()
            return redirect(reverse('editor:index'))

    return redirect(reverse('editor:open_project', kwargs={'project_id': project_id}))


@login_required
def open_project(request, project_id):
    if request.POST:
        data = json.loads(request.POST['json'])
        if 'tasks_table' in data:
            project = Project.objects.get(id=project_id)
            if len(data['tasks_table']) == project.number_of_tasks:
                for number, task_id in enumerate(data['tasks_table']):
                    task = ProjectTask.objects.get(id=task_id)
                    task.number = number + 1
                    task.save()

    template = loader.get_template('editor/tasks_table.html')

    context_table = {
        'type': 'tasks-list',
        'class': 'tasks-list',
        'columns': ['№', 'Название', 'Упражнений', 'Баллы'],
        'rows': []
    }

    is_empty = True

    for task in ProjectTask.objects.filter(project_id=project_id).order_by('number'):
        context_table['rows'].append(task.get_json())
        is_empty = False

    context = {
        'project': Project.objects.get(id=project_id),
        'tasks_table': template.render(context_table),
        'is_empty': is_empty
    }
    return render(request, 'editor/project/project_page.html', context)


@login_required
def create_task(request, project_id):
    if request.POST:

        project = Project.objects.get(id=project_id)
        task = ProjectTask(project=project)

        form = CreationTaskForm(request.POST, instance=task)

        if project.create_task(form):
            project.number_of_tasks += 1
            project.save()
            return redirect(reverse('editor:open_task', kwargs={'project_id': project_id, 'task_id': task.id}))

    return redirect(reverse('editor:open_project', kwargs={'project_id': project_id}))


@login_required
def remove_task(request, project_id, task_id):
    if request.POST:
        selected_task = ProjectTask.objects.get(id=task_id)
        number = selected_task.number
        for task in ProjectTask.objects.filter(project_id=project_id, number__gt=number).order_by('number'):
            task.number = number
            task.save()
            number += 1
        selected_task.delete()

        project = Project.objects.get(id=project_id)
        project.number_of_tasks -= 1
        project.save()

        return redirect(reverse('editor:open_project', kwargs={'project_id': project_id}))

    return redirect(reverse('editor:open_task', kwargs={'project_id': project_id, 'task_id': task_id}))


@login_required
def edit_project(request, project_id):
    if not request.POST:
        context = {
            'project': Project.objects.get(id=project_id)
        }
        return render(request, 'editor/project/project_edit.html', context)

    project = Project.objects.get(id=project_id)
    form = EditProjectInfo(request.POST, request.FILES, instance=project)

    project.edit_info(form)

    return redirect(reverse('editor:open_project', kwargs={'project_id': project_id}))


@login_required
def publish_project(request, project_id):
    project = Project.objects.get(id=project_id)
    project.publish()

    return redirect(reverse('editor:open_project', kwargs={'project_id': project_id}))



@login_required
def editor_not_allowed(request):
    return render(request, 'editor/editor_not_allowed.html')


@login_required
def templates(request):
    return render(request, 'develop_page.html')


@login_required
def stats(request):
    return render(request, 'develop_page.html')


@login_required
def editor_modal_window(request):
    return render(request, 'modal_window.html')


@login_required
def edit_task(request, project_id, task_id):
    if not request.POST:
        context = {
            'project': Project.objects.get(id=project_id),
            'task': ProjectTask.objects.get(id=task_id)
        }
        return render(request, 'editor/project/task/task_edit.html', context)

    task = ProjectTask.objects.get(id=task_id)
    form = EditTaskInfo(request.POST, request.FILES, instance=task)

    task.edit_info(form)

    return redirect(reverse('editor:open_task', kwargs={'project_id': project_id, 'task_id': task_id}))


@login_required
def open_task(request, project_id, task_id):
    if request.POST:
        data = json.loads(request.POST['json'])
        if 'elements-ordering' in data:
            number_of_elements = ProjectTaskElement.objects.filter(task_id=task_id).count()
            print(number_of_elements)
            if len(data['elements-ordering']) == number_of_elements:
                for index, elem_id in enumerate(data['elements-ordering']):
                    element = ProjectTaskElement.objects.get(element_id=elem_id)
                    element.order = index + 1
                    element.save()

    context = {
        'project': Project.objects.get(id=project_id),
        'task': ProjectTask.objects.get(id=task_id),
        'elements': map(lambda x: x.get_child(), ProjectTaskElement.objects.filter(task_id=task_id).order_by('order')),
        'creation_exercise_form': CreationExerciseForm(),
        'creation_element_form': CreationStaticElementForm()
    }

    print(context['elements'])

    return render(request, 'editor/project/task/task_page.html', context)


@login_required
def upload_project_description(request, project_id):

    form = CheckMarkDownForm(request.POST)

    if form.is_valid():
        project = Project.objects.get(id=project_id)
        project.description_md = request.POST.get('markdown_field')
        project.save()

    # return redirect(reverse('editor:open_project', kwargs={'project_id': project_id}))
    return JsonResponse({})


@login_required
def upload_task_description(request, project_id, task_id):

    form = CheckMarkDownForm(request.POST)

    if form.is_valid():
        task = ProjectTask.objects.get(id=task_id)
        task.description_md = request.POST.get('markdown_field')
        task.save()

    return JsonResponse({})


@login_required
def create_element(request, project_id, task_id):
    if request.POST:
        form = CreationStaticElementForm(request.POST)

        task = ProjectTask.objects.get(id=task_id)
        task.create_element(form)

    return redirect(reverse('editor:open_task', kwargs={'project_id': project_id, 'task_id': task_id}))


@login_required
def create_exercise(request, project_id, task_id):
    if request.POST:
        form = CreationExerciseForm(request.POST)

        task = ProjectTask.objects.get(id=task_id)
        task.create_exercise(form)

    return redirect(reverse('editor:open_task', kwargs={'project_id': project_id, 'task_id': task_id}))


@login_required
def remove_element(request, project_id, task_id):
    if request.POST and request.POST.get('element_id', False):
        elem_id = request.POST.get('element_id')
        selected_element = ProjectTaskElement.objects.get(element_id=elem_id)
        order = selected_element.order
        for element in ProjectTaskElement.objects.filter(task_id=task_id, order__gt=order).order_by('order'):
            element.order = order
            element.save()
            order += 1
        selected_element.delete()
        return redirect(reverse('editor:open_task', kwargs={'project_id': project_id, 'task_id': task_id}))

    return redirect(reverse('editor:open_task', kwargs={'project_id': project_id, 'task_id': task_id}))


@login_required
def change_element(request, project_id, task_id):
    print(request.POST)

templates/editor/project/project_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ project.project_name }}{% endblock %}

{% block css_styles %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'table.css' %}">
    <link rel="stylesheet" href="{% static 'editor/editor.css' %}">
    <link rel="stylesheet" href="{% static 'editor/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/header.css' %}">
    <link rel="stylesheet" href="{% static 'editor/project/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/project/edit_page.css' %}">
{% endblock %}

{% block content %}

    {% include 'editor/header.html' %}

    <div class="content">

        <p class="path"><a href="{% url 'editor:open_project' project_id=project.id %}" class="active-link">{{ project.project_name }}</a></p>

        <section class="preview-project">
            <main>
                <img src="/media/{{ project.icon }}" class="image_icon project-icon"/>
                <form class="project-info" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <div class="field">
                        <p class="field_name">Название теста</p>
                        <input type="text" name="name" maxlength="50" value="{{ project.name }}"/>
                    </div>
                    <div class="field">
                        <p class="field_name">Описание</p>
                        <textarea name="description" class="description">{{ project.description }}</textarea>
                    </div>
                    <div class="button button-secondary upload-file-button">Загрузить иконку</div>
                    <input type="file" class="file-uploader" name="icon">
                    <input type="submit" class="button buttons-submit" value="Сохранить"></input>
                </form>
            </main>
        </section>

    </div>

{% endblock %}

{% block js_scripts %}
    <script src="{% static 'editor/creation_page/script.js' %}"></script>
{% endblock %}

templates/editor/project/project_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ project.project_name }}{% endblock %}

{% block css_styles %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'table.css' %}">
    <link rel="stylesheet" href="{% static 'modal_window.css' %}">
    <link rel="stylesheet" href="{% static 'editor/editor.css' %}">
    <link rel="stylesheet" href="{% static 'editor/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/header.css' %}">
    <link rel="stylesheet" href="{% static 'editor/project/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/project/simplemde.min.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-min.css' %}">
{% endblock %}

{% block content %}

    {% include 'editor/header.html' %}

    <div class="content">

        <p class="path">{{ project.project_name }}</p>

        <section class="preview-project">
            <main>
                <div class="project-icon" style="--icon-url: url('/media/{{ project.icon }}')"></div>
                <div class="project-info">
                    <h2 class="name">{{ project.name }}</h2>
                    <p class="description">{{ project.description }}</p>
                </div>
            </main>
            <div class="buttons-edit">
                <div class="button button-change-info" data-url="{% url 'editor:edit_project' project_id=project.id %}"></div>
                <div class="button button-remove" data-modalwindow="#remove_project"></div>
            </div>
        </section>

        <section class="tabs-menu unselectable">
            <header class="tabs-buttons">
                <h2 data-content="project-tasks" class="tab-button active">Задания</h2>
                <h2 data-content="edit-info" class="tab-button">Описание</h2>
                <h2 data-content="project-settings" class="tab-button">Настройки</h2>
            </header>
            <div class="tabs-line"></div>
        </section>

        <section class="tab project-tasks">

            {% if not is_empty %}

                <main>
                    {{ tasks_table }}
                </main>

            {% endif %}

            <div class="button button-secondary button-create-task" data-modalwindow="#creation_task">
                Создать задание
            </div>

            <div class="editor-bar hidden">
                <div class="content-relative">
                    <div class="button button-save-changes">Сохранить изменения</div>
                </div>
            </div>
        </section>

        <section class="tab edit-info tab-relative not-visible" id="#edit-info">
            <form action="upload_description/" method="POST" id="edit-info-form">
                {% csrf_token %}
                <button type="sumbit" name="SEND UPDATES" class="button button-save-md not-allowed">Сохранить</button>
                <textarea id="edit-info" name="markdown_field">
{{ project.description_md }}</textarea>
            </form>
        </section>

        <section class="tab project-settings hidden">
            <p>Тут находятся настройки</p>
        </section>

        {% csrf_token %}

    </div>

    {% include 'editor/project/modal_window/remove_project.html' %}
    {% include 'editor/project/modal_window/creation_task.html' %}

    {% include 'footer.html' %}

{% endblock %}

{% block js_scripts %}
    <script src="{% static 'editor/changes.js' %}"></script>
{#    <script src="{% static 'editor/project.js' %}"></script>#}
    <script src="{% static 'editor/editor_object.js' %}"></script>
    <script src="{% static 'editor/project/tasks_table.js' %}"></script>
    <script src="{% static 'editor/project/tabs-menu.js' %}"></script>
    <script>
        let changesManager = new ChangesManager('.editor-bar');

        let table = new TasksTable('tasks_table');
        changesManager.addElement(table)
        table.setManager(changesManager)

        let button = document.querySelector('.button-save-changes');
        button.onclick = function () {
            changesManager.sendUpdates()
        };

    </script>
    <script src="{% static 'editor/project/simplemde.min.js' %}"></script>
    <script src="{% static 'editor/project/md-editor.js' %}"></script>
{% endblock %}